name: CI and Tag-Gated Release

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t davidtang-ai .

      - name: Test container startup
        run: |
          docker run -d --name test-container -p 8080:8080 davidtang-ai
          sleep 5
          curl -f http://localhost:8080/api/content || exit 1
          docker stop test-container
          docker rm test-container

  create-release-tag:
    name: Create release tag (triggers Cloud Build)
    needs: test-build
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create and push tag
        env:
          SHA_SHORT: ${{ github.sha }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          TAG="release-$(date +%Y%m%d%H%M%S)-${SHA_SHORT::7}"
          echo "Creating tag: $TAG"
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"

    # Configure Google Cloud Build to trigger on tags matching: release-*